export const UK_ESELON_1 = [
  { id: 1, name: 'Sekretariat Jenderal' },
  { id: 2, name: 'Direktorat Jenderal Penataan Ruang Laut' },
  { id: 3, name: 'Direktorat Jenderal Pengelolaan Kelautan' },
  { id: 4, name: 'Direktorat Jenderal Perikanan Tangkap' },
  { id: 5, name: 'Direktorat Jenderal Perikanan Budi Daya' },
  {
    id: 6,
    name:
      'Direktorat Jenderal Penguatan Daya Saing Produk Kelautan dan Perikanan',
  },
  {
    id: 7,
    name: 'Direktorat Jenderal Pengawasan Sumber Daya Kelautan dan Perikanan',
  },
  { id: 8, name: 'Inspektorat Jenderal' },
  {
    id: 9,
    name:
      'Badan Penyuluhan dan Pengembangan Sumber Daya Manusia Kelautan dan Perikanan',
  },
  {
    id: 10,
    name: 'Badan Pengendalian dan Pengawasan Mutu Hasil Kelautan dan Perikanan',
  },
]

export const UK_ESELON_2: { [key: string]: string[] } = {
  'Sekretariat Jenderal': [
    'Pusat Kebijakan Strategis',
    'Biro Perencanaan',
    'Biro Keuangan dan Barang Milik Negara',
    'Biro Sumber Daya Manusia Aparatur dan Organisasi',
    'Biro Hukum',
    'Biro Hubungan Masyarakat dan Kerja Sama Luar Negeri',
    'Biro Umum dan Pengadaan Barang/Jasa',
    'Pusat Data dan Informasi',
    'Lembaga Pengelola Modal Usaha Kelautan dan Perikanan',
  ],
  'Direktorat Jenderal Penataan Ruang Laut': [
    'Sekretariat Direktorat Jenderal Penataan Ruang Laut',
    'Direktorat Perencanaan Ruang Perairan',
    'Direktorat Pemanfaatan Ruang Pesisir dan Pulau-Pulau Kecil',
    'Direktorat Pengendalian Pemanfaatan Ruang Laut',
    'Direktorat Pemanfaatan Ruang Kolom Perairan dan Dasar Laut',
    'Direktorat Pembinaan Penataan Ruang Laut',
  ],
  'Direktorat Jenderal Pengelolaan Kelautan': [
    'Sekretariat Direktorat Jenderal Pengelolaan Kelautan',
    'Direktorat Sumber Daya Kelautan',
    'Direktorat Konservasi Spesies dan Genetik',
    'Direktorat Konservasi Ekosistem',
    'Direktorat Jasa Bahari',
    'Direktorat Pesisir dan Pulau-Pulau Kecil',
  ],
  'Direktorat Jenderal Perikanan Tangkap': [
    'Sekretariat Ditjen Perikanan Tangkap',
    'Direktorat Pengelolaan Sumberdaya Ikan',
    'Direktorat Kepelabuhanan Perikanan',
    'Direktorat Usaha Penangkapan Ikan',
    'Direktorat Kapal Perikanan dan Alat Penangkapan Ikan',
    'Direktorat Perlindungan dan Pemberdayaan Nelayan',
  ],
  'Direktorat Jenderal Perikanan Budi Daya': [
    'Sekretariat Ditjen Perikanan Budi Daya',
    'Direktorat Ikan Air Tawar',
    'Direktorat Ikan Air Payau',
    'Direktorat Ikan Air Laut',
    'Direktorat Rumput Laut',
    'Direktorat Prasarana dan Sarana',
  ],
  'Direktorat Jenderal Penguatan Daya Saing Produk Kelautan dan Perikanan': [
    'Sekretariat Ditjen Penguatan Daya Saing Produk Kelautan Dan Perikanan',
    'Direktorat Pemberdayaan Usaha',
    'Direktorat Logistik',
    'Direktorat Pengolahan',
  ],
  'Direktorat Jenderal Pengawasan Sumber Daya Kelautan dan Perikanan': [
    'Sekretariat Ditjen Pengawasan Sumber Daya Kelautan dan Perikanan',
    'Direktorat Penanganan Pelanggaran',
    'Direktorat Pengawasan Sumber Daya Kelautan',
    'Direktorat Pengendalian Operasi Armada',
    'Direktorat Pengawasan Sumber Daya Perikanan',
    'Direktorat Prasarana dan Sarana Pengawasan',
  ],
  'Inspektorat Jenderal': [
    'Sekretariat Inspektorat Jenderal',
    'Inspektorat I',
    'Inspektorat Ii',
    'Inspektorat Iii',
    'Inspektorat Iv',
    'Inspektorat V',
  ],
  'Badan Penyuluhan dan Pengembangan Sumber Daya Manusia Kelautan dan Perikanan': [
    'Sekretariat Badan Penyuluhan dan Pengembangan Sumber Daya Manusia Kelautan dan Perikanan',
    'Pusat Pendidikan Kelautan dan Perikanan',
    'Pusat Penyuluhan Kelautan dan Perikanan',
    'Pusat Pelatihan Kelautan dan Perikanan',
    'Pusat Standarisasi dan Sertifikasi Sumber Daya Manusia Kelautan dan Perikanan',
  ],
  'Badan Pengendalian dan Pengawasan Mutu Hasil Kelautan dan Perikanan': [
    'Sekretariat Badan Pengendalian dan Pengawasan Mutu Hasil Kelautan dan Perikanan',
    'Pusat Manajemen Mutu',
    'Pusat Pengendalian dan Pengawasan Mutu Pascapanen',
    'Pusat Pengendalian dan Pengawasan Mutu Produksi Primer',
  ],
}

export const UK_ESELON_3: { [key: string]: string[] } = {
  'Badan Penyuluhan dan Pengembangan Sumber Daya Manusia Kelautan dan Perikanan': [
    'Balai Pelatihan dan Penyuluhan Perikanan Banyuwangi',
    'Balai Pelatihan dan Penyuluhan Perikanan Ambon',
    'Balai Pelatihan dan Penyuluhan Perikanan Bitung',
    'Balai Pelatihan dan Penyuluhan Perikanan Medan',
    'Balai Pelatihan dan Penyuluhan Perikanan Tegal',
    'Balai Pendidikan dan Pelatihan Aparatur Sukamandi',
    'Politeknik Kelautan dan Perikanan Karawang',
    'Politeknik Kelautan dan Perikanan Bitung',
    'Politeknik Kelautan dan Perikanan Kupang',
    'Politeknik Kelautan dan Perikanan Sorong',
    'Politeknik Kelautan dan Perikanan Sidoarjo',
    'Politeknik Kelautan dan Perikanan Pangandaran',
    'Politeknik Ahli Usaha Perikanan',
    'Politeknik Kelautan dan Perikanan Bone',
    'Politeknik Kelautan dan Perikanan Jembrana',
    'Politeknik Kelautan dan Perikanan Dumai',
    'Sekolah Usaha Perikanan Menengah Negeri Tegal',
    'Sekolah Usaha Perikanan Menengah Negeri Sorong',
    'Sekolah Usaha Perikanan Menengah Negeri Kupang',
    'Sekolah Usaha Perikanan Menengah Negeri Pariaman',
    'Sekolah Usaha Perikanan Menengah Negeri Ladong Aceh',
    'Sekolah Usaha Perikanan Menengah Negeri Kota Agung',
    'Sekolah Usaha Perikanan Menengah Negeri Waiheru Ambon',
    'Balai Besar Riset Pengolahan Produk dan Bioteknologi Kelautan dan Perikanan',
    'Balai Besar Riset Budidaya Laut dan Penyuluhan Perikanan, Gondol Buleleng Singaraja',
    'Balai Besar Riset Sosial Ekonomi Kelautan dan Perikanan',
    'Balai Riset Pemulihan Sumber Daya Ikan, Jatiluhur Purwakarta',
    'Balai Riset Perikanan Budidaya Air Tawar dan Penyuluhan Perikanan, Bogor',
    'Balai Riset Perikanan Laut, Jakarta',
    'Balai Riset Pemuliaan Ikan',
    'Balai Riset Perikanan Budidaya Air Payau dan Penyuluhan Perikanan, Maros',
    'Balai Riset Perikanan Perairan Umum dan Penyuluhan Perikanan, Palembang',
    'Balai Riset Budidaya Ikan Hias, Depok',
    'Loka Riset Perikanan Tuna, Benoa',
    'Loka Riset Sumberdaya dan Kerentanan Pesisir, Padang',
    'Loka Perekayasaan Teknologi Kelautan, Wakatobi',
    'Loka Riset Mekanisasi Pengolahan Hasil Perikanan',
    'Loka Riset Budidaya Rumput Laut, Boalemo Gorontalo',
    'Akademi Komunitas Kelautan dan Perikanan Wakatobi',
  ],
}
