export type User = {
  IdUsers: number
  Nama: string
  NoTelpon: number
  Email: string
  Password: string
  Kota: string
  Provinsi: string
  Alamat: string
  Nik: number
  TempatLahir: string
  TanggalLahir: string
  JenisKelamin: string
  Pekerjaan: string
  GolonganDarah: string
  StatusMenikah: string
  Kewarganegaraan: string
  IbuKandung: string
  NegaraTujuanBekerja: string
  PendidikanTerakhir: string
  Agama: string
  Foto: string
  Ktp: string
  KK: string
  SuratKesehatan: string
  Status: string
  CreateAt: string
  UpdateAt: string
  Ijazah: string
  KusukaUsers: string
  Pelatihan: UserPelatihan[]
}

export type UserPelatihan = {
  CreatedAt: string
  CreteAt?: string
  IdUserPelatihan: number
  IdPelatihan: number
  FileSertifikat?: string
  IdUsers: number
  IsActice: string
  PenyelenggaraPelatihan?: string
  TanggalMulai?: string
  PendidikanTerakhir?: string
  IsKeterangan: string
  MetodoPembayaran: string
  NilaiPraktek: number
  NilaiTeory: number
  NoRegistrasi: string
  NoSertifikat: string
  TanggalSertifikat?: string
  PostTest: number
  PreTest: number
  JenisKelamin?: string
  StatusPembayaran: string
  UpdateAt: string
  WaktuPembayaran: string
  NamaPelatihan: string
  DetailPelatihan: string
  BidangPelatihan?: string
  Keterangan: string
  Nama: string
  TotalBayar: string
  CodeAksess?: string
  Provinsi?: string
  TempatTanggalLahir?: string
  JenisProgram?: string
  Program?: string
  DukunganProgramPrioritas?: string
}
